title: Atharv Chowdhary
description: Personal website of Atharv Chowdhary
url: "https://achowd32.github.io"
baseurl: ""

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
